
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FROM = 13;
  public static final int COLUMN = 62;
  public static final int TYPE = 33;
  public static final int IMPLEMENTS = 9;
  public static final int DATATYPE_COMPLEX = 107;
  public static final int PARENT = 5;
  public static final int QUERY_CONDITIONS = 55;
  public static final int TABLE = 63;
  public static final int LLAVE_IZQ = 92;
  public static final int COR_IZQ = 94;
  public static final int SEMI = 99;
  public static final int GET = 41;
  public static final int LAMBDA = 87;
  public static final int PASS = 11;
  public static final int NAMESPACE = 44;
  public static final int ASSIGNMENT = 25;
  public static final int ENUM = 7;
  public static final int ITERATE = 103;
  public static final int COMMA = 97;
  public static final int JOIN = 66;
  public static final int PAR_DER = 91;
  public static final int MEMBERSHIP = 34;
  public static final int UNARY = 24;
  public static final int INCREMENT = 49;
  public static final int INTEGER = 117;
  public static final int LOGICAL = 27;
  public static final int DATATYPE_CHAR = 109;
  public static final int BACKUP = 59;
  public static final int VIEW = 61;
  public static final int INSTANCE = 32;
  public static final int ERROR = 121;
  public static final int GOTO = 42;
  public static final int PACKAGE = 20;
  public static final int END_COMMENT = 73;
  public static final int WHILE_LOOP = 102;
  public static final int CHARACTER = 116;
  public static final int HANDLER = 36;
  public static final int ACCESMOD = 2;
  public static final int CONDITIONALQUERY = 54;
  public static final int CLASS = 4;
  public static final int SELECT = 65;
  public static final int DATATYPE_STRING = 108;
  public static final int PARTIAL = 48;
  public static final int ALIAS = 18;
  public static final int ALTER = 56;
  public static final int INDEX = 67;
  public static final int UNION = 70;
  public static final int LINE_COMMENT = 71;
  public static final int EXTENDS = 8;
  public static final int MODULE = 43;
  public static final int DELETE = 15;
  public static final int DECIMAL = 118;
  public static final int INTERFACE = 6;
  public static final int BOOLEAN = 113;
  public static final int NONACCESMOD = 3;
  public static final int DO_LOOP = 101;
  public static final int EXECUTE = 88;
  public static final int CONDITIONAL = 75;
  public static final int SWITCH = 78;
  public static final int VARIABLE = 112;
  public static final int VOID = 86;
  public static final int ADD = 52;
  public static final int RETURN = 89;
  public static final int MODIFIER = 37;
  public static final int TERNARY = 30;
  public static final int TRY = 82;
  public static final int POINT = 96;
  public static final int BREAK = 80;
  public static final int CONDITION_CONSEQ = 76;
  public static final int SPECIAL_COMMENT = 74;
  public static final int STORAGE = 38;
  public static final int REFERENCE = 17;
  public static final int NULL = 114;
  public static final int DATATYPE_DECIMAL = 106;
  public static final int PAR_IZQ = 90;
  public static final int NEGATION = 28;
  public static final int EOF = 0;
  public static final int ARITHMETIC = 23;
  public static final int THIS = 16;
  public static final int ASYNCHRONOUS = 19;
  public static final int DEFAULT = 81;
  public static final int LLAVE_DER = 93;
  public static final int DATATYPE_MISC = 110;
  public static final int FUNCTION = 85;
  public static final int PRINT = 21;
  public static final int COR_DER = 95;
  public static final int OPERATOR = 46;
  public static final int DATATYPE_INT = 105;
  public static final int IMPORT = 12;
  public static final int FOR_LOOP = 100;
  public static final int DEBUG = 50;
  public static final int error = 1;
  public static final int CONTINUE = 10;
  public static final int ID = 120;
  public static final int DATATYPE_BOOL = 104;
  public static final int IDENTITY = 31;
  public static final int CAST = 39;
  public static final int DATA_STRUCTURE = 111;
  public static final int OF = 45;
  public static final int COLON = 98;
  public static final int DATABASE = 64;
  public static final int START_COMMENT = 72;
  public static final int CREATE = 14;
  public static final int TRY_CONSEQUENCE = 83;
  public static final int NULLISH = 29;
  public static final int CASE = 79;
  public static final int LIMIT = 68;
  public static final int EXCEPTION = 84;
  public static final int OPTION = 47;
  public static final int UPDATE = 69;
  public static final int INSERT = 57;
  public static final int STRING = 115;
  public static final int CONSEQUENCE = 77;
  public static final int RANGE = 60;
  public static final int BITWISE = 35;
  public static final int COMPARISON = 22;
  public static final int SORT = 58;
  public static final int COMPLEX = 119;
  public static final int STRUCTURE = 51;
  public static final int CONSTRAINT = 53;
  public static final int EVENT = 40;
  public static final int ASSIGN_OPT = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ACCESMOD",
  "NONACCESMOD",
  "CLASS",
  "PARENT",
  "INTERFACE",
  "ENUM",
  "EXTENDS",
  "IMPLEMENTS",
  "CONTINUE",
  "PASS",
  "IMPORT",
  "FROM",
  "CREATE",
  "DELETE",
  "THIS",
  "REFERENCE",
  "ALIAS",
  "ASYNCHRONOUS",
  "PACKAGE",
  "PRINT",
  "COMPARISON",
  "ARITHMETIC",
  "UNARY",
  "ASSIGNMENT",
  "ASSIGN_OPT",
  "LOGICAL",
  "NEGATION",
  "NULLISH",
  "TERNARY",
  "IDENTITY",
  "INSTANCE",
  "TYPE",
  "MEMBERSHIP",
  "BITWISE",
  "HANDLER",
  "MODIFIER",
  "STORAGE",
  "CAST",
  "EVENT",
  "GET",
  "GOTO",
  "MODULE",
  "NAMESPACE",
  "OF",
  "OPERATOR",
  "OPTION",
  "PARTIAL",
  "INCREMENT",
  "DEBUG",
  "STRUCTURE",
  "ADD",
  "CONSTRAINT",
  "CONDITIONALQUERY",
  "QUERY_CONDITIONS",
  "ALTER",
  "INSERT",
  "SORT",
  "BACKUP",
  "RANGE",
  "VIEW",
  "COLUMN",
  "TABLE",
  "DATABASE",
  "SELECT",
  "JOIN",
  "INDEX",
  "LIMIT",
  "UPDATE",
  "UNION",
  "LINE_COMMENT",
  "START_COMMENT",
  "END_COMMENT",
  "SPECIAL_COMMENT",
  "CONDITIONAL",
  "CONDITION_CONSEQ",
  "CONSEQUENCE",
  "SWITCH",
  "CASE",
  "BREAK",
  "DEFAULT",
  "TRY",
  "TRY_CONSEQUENCE",
  "EXCEPTION",
  "FUNCTION",
  "VOID",
  "LAMBDA",
  "EXECUTE",
  "RETURN",
  "PAR_IZQ",
  "PAR_DER",
  "LLAVE_IZQ",
  "LLAVE_DER",
  "COR_IZQ",
  "COR_DER",
  "POINT",
  "COMMA",
  "COLON",
  "SEMI",
  "FOR_LOOP",
  "DO_LOOP",
  "WHILE_LOOP",
  "ITERATE",
  "DATATYPE_BOOL",
  "DATATYPE_INT",
  "DATATYPE_DECIMAL",
  "DATATYPE_COMPLEX",
  "DATATYPE_STRING",
  "DATATYPE_CHAR",
  "DATATYPE_MISC",
  "DATA_STRUCTURE",
  "VARIABLE",
  "BOOLEAN",
  "NULL",
  "STRING",
  "CHARACTER",
  "INTEGER",
  "DECIMAL",
  "COMPLEX",
  "ID",
  "ERROR"
  };
}

